//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrInfra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceLogsNewForMobile
    {
        public int AttendanceLogId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string Duration { get; set; }
        public string HeadId { get; set; }
        public string AddressIn { get; set; }
        public string LattitudeIn { get; set; }
        public string LongitudeIn { get; set; }
        public string AddressOut { get; set; }
        public string LattitudeOut { get; set; }
        public string LongitudeOut { get; set; }
        public string AttendanceStatus { get; set; }
        public string Modeofpunchin { get; set; }
        public string InImage { get; set; }
        public Nullable<System.DateTime> shiftintime { get; set; }
        public Nullable<System.DateTime> shiftouttime { get; set; }
        public Nullable<System.DateTime> ManagerActionOn { get; set; }
        public string ManagerRemarks { get; set; }
        public string PolygonIn { get; set; }
        public string PolygonOut { get; set; }
        public string MarkedByIn { get; set; }
        public string MarkedByOut { get; set; }
        public string ModeofpunchOut { get; set; }
        public Nullable<System.DateTime> BioMetricIn { get; set; }
        public Nullable<System.DateTime> BioMetricOut { get; set; }
        public string ActionHappen { get; set; }
        public string ByWhomActiondone { get; set; }
    }
}
