//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrInfra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner_image
    {
        public int id { get; set; }
        public string imageUrl { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string Title { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> Fromdate { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public string Description { get; set; }
        public string BackgroundImage { get; set; }
    }
}
