//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrInfra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiometricAttendance
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> PunchInDate { get; set; }
        public Nullable<System.TimeSpan> PunchInTime { get; set; }
        public Nullable<System.DateTime> PunchOutDate { get; set; }
        public Nullable<System.TimeSpan> PunchOutTime { get; set; }
        public string CustRegularized { get; set; }
    }
}
