//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrInfra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public string EmployeeId { get; set; }
        public string EmpName { get; set; }
        public string DateOfJoining { get; set; }
        public string EmpEmailId { get; set; }
        public string EmpMobile { get; set; }
        public string MangerID { get; set; }
        public string MangerName { get; set; }
        public string MangerEmail { get; set; }
        public string ManagerMobile { get; set; }
        public string HRID { get; set; }
        public string HRName { get; set; }
        public string HRManagerEmail { get; set; }
        public string HRManagerMobile { get; set; }
        public string DateOfBirth { get; set; }
        public string Company { get; set; }
        public string Department { get; set; }
        public string GradeCode { get; set; }
        public string Branch { get; set; }
        public string Designation { get; set; }
        public string Sex { get; set; }
        public string BUCode { get; set; }
    }
}
