//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrInfra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GInfraEntities : DbContext
    {
        public GInfraEntities()
            : base("name=GInfraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendanceLogsNewForMobile> AttendanceLogsNewForMobiles { get; set; }
        public virtual DbSet<attendancestatusmaster> attendancestatusmasters { get; set; }
        public virtual DbSet<Banner_image> Banner_image { get; set; }
        public virtual DbSet<BiometricAttendance> BiometricAttendances { get; set; }
        public virtual DbSet<DoublePunchMaster> DoublePunchMasters { get; set; }
        public virtual DbSet<HR_Announcement> HR_Announcement { get; set; }
        public virtual DbSet<MasterPassword> MasterPasswords { get; set; }
        public virtual DbSet<MobileDevicelog> MobileDevicelogs { get; set; }
        public virtual DbSet<Monthly> Monthlies { get; set; }
        public virtual DbSet<Polygon> Polygons { get; set; }
        public virtual DbSet<ReasonMaster> ReasonMasters { get; set; }
        public virtual DbSet<RoleDefine> RoleDefines { get; set; }
        public virtual DbSet<ShiftMaster> ShiftMasters { get; set; }
        public virtual DbSet<AppversionMaster> AppversionMasters { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<iosAppversionMaster> iosAppversionMasters { get; set; }
        public virtual DbSet<MobileDetail> MobileDetails { get; set; }
        public virtual DbSet<Roaster> Roasters { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<SiteMaster> SiteMasters { get; set; }
    
        public virtual int BioMetricDataPullPush()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BioMetricDataPullPush");
        }
    
        public virtual int BioMetricDataPullPushtemp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BioMetricDataPullPushtemp");
        }
    
        public virtual int deletedata(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletedata", useridParameter);
        }
    
        public virtual ObjectResult<string> Get_UserId(string authKey)
        {
            var authKeyParameter = authKey != null ?
                new ObjectParameter("authKey", authKey) :
                new ObjectParameter("authKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_UserId", authKeyParameter);
        }
    
        public virtual ObjectResult<getAttendanceListByReportingHead_Result> getAttendanceListByReportingHead(string headId, string employee, string fromdate, string todate, string status)
        {
            var headIdParameter = headId != null ?
                new ObjectParameter("HeadId", headId) :
                new ObjectParameter("HeadId", typeof(string));
    
            var employeeParameter = employee != null ?
                new ObjectParameter("employee", employee) :
                new ObjectParameter("employee", typeof(string));
    
            var fromdateParameter = fromdate != null ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(string));
    
            var todateParameter = todate != null ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAttendanceListByReportingHead_Result>("getAttendanceListByReportingHead", headIdParameter, employeeParameter, fromdateParameter, todateParameter, statusParameter);
        }
    
        public virtual ObjectResult<GetBirthdayData_Result> GetBirthdayData(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBirthdayData_Result>("GetBirthdayData", useridParameter);
        }
    
        public virtual ObjectResult<getuserattendancebyhead_Result> getuserattendancebyhead(string headid)
        {
            var headidParameter = headid != null ?
                new ObjectParameter("headid", headid) :
                new ObjectParameter("headid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getuserattendancebyhead_Result>("getuserattendancebyhead", headidParameter);
        }
    
        public virtual int InsertAttendanceDATA_NEW12am()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAttendanceDATA_NEW12am");
        }
    
        public virtual int InsertAttendanceDATA_NEW12pm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAttendanceDATA_NEW12pm");
        }
    
        public virtual int InsertAttendanceDATA_NEWtemp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAttendanceDATA_NEWtemp");
        }
    
        public virtual int Sftpemployeepassword()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sftpemployeepassword");
        }
    
        public virtual ObjectResult<sp_ApproveorRejectAttendance_Result> sp_ApproveorRejectAttendance(string attendanceLogId, string managercomment, string action, string userid)
        {
            var attendanceLogIdParameter = attendanceLogId != null ?
                new ObjectParameter("AttendanceLogId", attendanceLogId) :
                new ObjectParameter("AttendanceLogId", typeof(string));
    
            var managercommentParameter = managercomment != null ?
                new ObjectParameter("managercomment", managercomment) :
                new ObjectParameter("managercomment", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApproveorRejectAttendance_Result>("sp_ApproveorRejectAttendance", attendanceLogIdParameter, managercommentParameter, actionParameter, useridParameter);
        }
    
        public virtual ObjectResult<sp_Attendancelistbyuser_Result> sp_Attendancelistbyuser(string loginId, string fromdate, string todate)
        {
            var loginIdParameter = loginId != null ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(string));
    
            var fromdateParameter = fromdate != null ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(string));
    
            var todateParameter = todate != null ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Attendancelistbyuser_Result>("sp_Attendancelistbyuser", loginIdParameter, fromdateParameter, todateParameter);
        }
    
        public virtual ObjectResult<sp_bannerimage_Result> sp_bannerimage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bannerimage_Result>("sp_bannerimage");
        }
    
        public virtual ObjectResult<sp_checkcurrentstatus_Result> sp_checkcurrentstatus(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_checkcurrentstatus_Result>("sp_checkcurrentstatus", useridParameter);
        }
    
        public virtual int sp_checkhours()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_checkhours");
        }
    
        public virtual ObjectResult<string> sp_forgetpassword(string dob, string tmc)
        {
            var dobParameter = dob != null ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(string));
    
            var tmcParameter = tmc != null ?
                new ObjectParameter("tmc", tmc) :
                new ObjectParameter("tmc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_forgetpassword", dobParameter, tmcParameter);
        }
    
        public virtual ObjectResult<sp_getheaddatabyuserid_Result> sp_getheaddatabyuserid(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getheaddatabyuserid_Result>("sp_getheaddatabyuserid", useridParameter);
        }
    
        public virtual ObjectResult<sp_hrnotification_Result> sp_hrnotification(string branch)
        {
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_hrnotification_Result>("sp_hrnotification", branchParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_InsertPolygon(string polygonJson, Nullable<int> siteId, ObjectParameter eRROR)
        {
            var polygonJsonParameter = polygonJson != null ?
                new ObjectParameter("PolygonJson", polygonJson) :
                new ObjectParameter("PolygonJson", typeof(string));
    
            var siteIdParameter = siteId.HasValue ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_InsertPolygon", polygonJsonParameter, siteIdParameter, eRROR);
        }
    
        public virtual ObjectResult<sp_login_Result> sp_login(string userid, string password, string authtoken, string devicetoken)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var authtokenParameter = authtoken != null ?
                new ObjectParameter("authtoken", authtoken) :
                new ObjectParameter("authtoken", typeof(string));
    
            var devicetokenParameter = devicetoken != null ?
                new ObjectParameter("devicetoken", devicetoken) :
                new ObjectParameter("devicetoken", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_login_Result>("sp_login", useridParameter, passwordParameter, authtokenParameter, devicetokenParameter);
        }
    
        public virtual ObjectResult<sp_logintemp_Result> sp_logintemp(string userid, string password, string authtoken, string devicetoken)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var authtokenParameter = authtoken != null ?
                new ObjectParameter("authtoken", authtoken) :
                new ObjectParameter("authtoken", typeof(string));
    
            var devicetokenParameter = devicetoken != null ?
                new ObjectParameter("devicetoken", devicetoken) :
                new ObjectParameter("devicetoken", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_logintemp_Result>("sp_logintemp", useridParameter, passwordParameter, authtokenParameter, devicetokenParameter);
        }
    
        public virtual int sp_mobiledevice(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mobiledevice", useridParameter);
        }
    
        public virtual ObjectResult<Sp_MonthlyAttendanceReports_Result> Sp_MonthlyAttendanceReports(string role, string loginId, string employeeId, string managerId, string hRId, string branch)
        {
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            var loginIdParameter = loginId != null ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            var managerIdParameter = managerId != null ?
                new ObjectParameter("ManagerId", managerId) :
                new ObjectParameter("ManagerId", typeof(string));
    
            var hRIdParameter = hRId != null ?
                new ObjectParameter("HRId", hRId) :
                new ObjectParameter("HRId", typeof(string));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MonthlyAttendanceReports_Result>("Sp_MonthlyAttendanceReports", roleParameter, loginIdParameter, employeeIdParameter, managerIdParameter, hRIdParameter, branchParameter);
        }
    
        public virtual ObjectResult<sp_polygon_Result> sp_polygon(string branch)
        {
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_polygon_Result>("sp_polygon", branchParameter);
        }
    
        public virtual ObjectResult<sp_ReasonsList_Result> sp_ReasonsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReasonsList_Result>("sp_ReasonsList");
        }
    
        public virtual ObjectResult<sp_updateUserPassword_Result> sp_updateUserPassword(string userID, string password, string oldpassword)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var oldpasswordParameter = oldpassword != null ?
                new ObjectParameter("Oldpassword", oldpassword) :
                new ObjectParameter("Oldpassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_updateUserPassword_Result>("sp_updateUserPassword", userIDParameter, passwordParameter, oldpasswordParameter);
        }
    
        public virtual ObjectResult<InsertAttendanceIn_Result> InsertAttendanceIn(string employeeId, string inTime, string headId, string addressIn, string lattitudeIn, string longitudeIn, string workStatus, string modeofpunchin, string punchinphotopath, string polygonIn, string action)
        {
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            var inTimeParameter = inTime != null ?
                new ObjectParameter("InTime", inTime) :
                new ObjectParameter("InTime", typeof(string));
    
            var headIdParameter = headId != null ?
                new ObjectParameter("HeadId", headId) :
                new ObjectParameter("HeadId", typeof(string));
    
            var addressInParameter = addressIn != null ?
                new ObjectParameter("AddressIn", addressIn) :
                new ObjectParameter("AddressIn", typeof(string));
    
            var lattitudeInParameter = lattitudeIn != null ?
                new ObjectParameter("LattitudeIn", lattitudeIn) :
                new ObjectParameter("LattitudeIn", typeof(string));
    
            var longitudeInParameter = longitudeIn != null ?
                new ObjectParameter("LongitudeIn", longitudeIn) :
                new ObjectParameter("LongitudeIn", typeof(string));
    
            var workStatusParameter = workStatus != null ?
                new ObjectParameter("WorkStatus", workStatus) :
                new ObjectParameter("WorkStatus", typeof(string));
    
            var modeofpunchinParameter = modeofpunchin != null ?
                new ObjectParameter("modeofpunchin", modeofpunchin) :
                new ObjectParameter("modeofpunchin", typeof(string));
    
            var punchinphotopathParameter = punchinphotopath != null ?
                new ObjectParameter("punchinphotopath", punchinphotopath) :
                new ObjectParameter("punchinphotopath", typeof(string));
    
            var polygonInParameter = polygonIn != null ?
                new ObjectParameter("PolygonIn", polygonIn) :
                new ObjectParameter("PolygonIn", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsertAttendanceIn_Result>("InsertAttendanceIn", employeeIdParameter, inTimeParameter, headIdParameter, addressInParameter, lattitudeInParameter, longitudeInParameter, workStatusParameter, modeofpunchinParameter, punchinphotopathParameter, polygonInParameter, actionParameter);
        }
    
        public virtual ObjectResult<InsertAttendanceOut_Result> InsertAttendanceOut(string employeeId, string outTime, string status, string addressOut, string lattitudeOut, string longitudeOut, string attendanceLogId, string modeofpunchin, string polygonOut, string action)
        {
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            var outTimeParameter = outTime != null ?
                new ObjectParameter("OutTime", outTime) :
                new ObjectParameter("OutTime", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var addressOutParameter = addressOut != null ?
                new ObjectParameter("AddressOut", addressOut) :
                new ObjectParameter("AddressOut", typeof(string));
    
            var lattitudeOutParameter = lattitudeOut != null ?
                new ObjectParameter("LattitudeOut", lattitudeOut) :
                new ObjectParameter("LattitudeOut", typeof(string));
    
            var longitudeOutParameter = longitudeOut != null ?
                new ObjectParameter("LongitudeOut", longitudeOut) :
                new ObjectParameter("LongitudeOut", typeof(string));
    
            var attendanceLogIdParameter = attendanceLogId != null ?
                new ObjectParameter("AttendanceLogId", attendanceLogId) :
                new ObjectParameter("AttendanceLogId", typeof(string));
    
            var modeofpunchinParameter = modeofpunchin != null ?
                new ObjectParameter("modeofpunchin", modeofpunchin) :
                new ObjectParameter("modeofpunchin", typeof(string));
    
            var polygonOutParameter = polygonOut != null ?
                new ObjectParameter("PolygonOut", polygonOut) :
                new ObjectParameter("PolygonOut", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsertAttendanceOut_Result>("InsertAttendanceOut", employeeIdParameter, outTimeParameter, statusParameter, addressOutParameter, lattitudeOutParameter, longitudeOutParameter, attendanceLogIdParameter, modeofpunchinParameter, polygonOutParameter, actionParameter);
        }
    
        public virtual int sp_notification(string userid, string type, string title, string description)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_notification", useridParameter, typeParameter, titleParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<string> sp_updateappversion(string type, string appversionid, string appversionurl)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var appversionidParameter = appversionid != null ?
                new ObjectParameter("appversionid", appversionid) :
                new ObjectParameter("appversionid", typeof(string));
    
            var appversionurlParameter = appversionurl != null ?
                new ObjectParameter("appversionurl", appversionurl) :
                new ObjectParameter("appversionurl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_updateappversion", typeParameter, appversionidParameter, appversionurlParameter);
        }
    
        public virtual ObjectResult<sp_mobiledetails_Result> sp_mobiledetails(string userid, string iMEI, Nullable<int> battery, string lastActivity, string lastLocation, string appVersion)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var iMEIParameter = iMEI != null ?
                new ObjectParameter("IMEI", iMEI) :
                new ObjectParameter("IMEI", typeof(string));
    
            var batteryParameter = battery.HasValue ?
                new ObjectParameter("Battery", battery) :
                new ObjectParameter("Battery", typeof(int));
    
            var lastActivityParameter = lastActivity != null ?
                new ObjectParameter("LastActivity", lastActivity) :
                new ObjectParameter("LastActivity", typeof(string));
    
            var lastLocationParameter = lastLocation != null ?
                new ObjectParameter("LastLocation", lastLocation) :
                new ObjectParameter("LastLocation", typeof(string));
    
            var appVersionParameter = appVersion != null ?
                new ObjectParameter("AppVersion", appVersion) :
                new ObjectParameter("AppVersion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mobiledetails_Result>("sp_mobiledetails", useridParameter, iMEIParameter, batteryParameter, lastActivityParameter, lastLocationParameter, appVersionParameter);
        }
    }
}
