//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrInfra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileDetail
    {
        public int id { get; set; }
        public string Userid { get; set; }
        public string IMEI { get; set; }
        public int Battery { get; set; }
        public System.DateTime LastActivity { get; set; }
        public string LastLocation { get; set; }
        public string AppVersion { get; set; }
    }
}
