//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrInfra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftMaster
    {
        public int Id { get; set; }
        public string UniqueShift { get; set; }
        public string SFShift { get; set; }
        public string ShiftExternalCode { get; set; }
    }
}
