//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrInfra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMaster
    {
        public int Id { get; set; }
        public string BUCode { get; set; }
        public string BUDescription { get; set; }
        public Nullable<double> Workinghours { get; set; }
        public Nullable<double> GracePeriod { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string lattitude { get; set; }
        public string longitute { get; set; }
    }
}
